package trial;
import javax.swing.*;
import java.sql.*;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author D. Dilsha Singh
 */
public class login extends javax.swing.JFrame {
Connection con;
    Statement st;
    PreparedStatement ps;
    ResultSet rs;
    public String username;
  
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        try{
Class.forName("oracle.jdbc.OracleDriver");
JOptionPane.showMessageDialog(this,"Driver Loaded!");
try {
//con = DriverManager.getConnection("jdbc:oracle:thin:@10.6.4.33:1521:orcl",
//        "cse1028","ssn");
con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE",
        "system","kushal");
JOptionPane.showMessageDialog(this,"Connected to Oracle database!");
}
catch (SQLException ex) {
Logger.getLogger(login.class.getName()).log(Level.SEVERE,null, ex);
JOptionPane.showMessageDialog(this,ex.getMessage());
}
}
        catch(ClassNotFoundException ex){
Logger.getLogger(login.class.getName()).log(Level.SEVERE,null, ex);
JOptionPane.showMessageDialog(this,ex.getMessage());

} 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        login = new javax.swing.JLabel();
        user_id = new javax.swing.JLabel();
        l_username = new javax.swing.JTextField();
        l_password = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        l_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        QUICKBITE = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        login.setText("        LOGIN");
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 141, -1));

        user_id.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        user_id.setText("USER NAME");
        getContentPane().add(user_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 83, -1));

        l_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(l_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 96, -1));

        l_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(l_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 96, -1));

        password.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        password.setText("PASSWORD");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 83, -1));

        l_login.setBackground(new java.awt.Color(51, 51, 255));
        l_login.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        l_login.setForeground(new java.awt.Color(255, 255, 255));
        l_login.setText("LOGIN");
        l_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_loginActionPerformed(evt);
            }
        });
        getContentPane().add(l_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 96, -1));

        jLabel1.setFont(new java.awt.Font("Vani", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("No Account? Create one");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 145, -1));

        register.setBackground(new java.awt.Color(51, 51, 255));
        register.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setText("REGISTER");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 44, 37, -1));

        QUICKBITE.setBackground(new java.awt.Color(51, 51, 255));
        QUICKBITE.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        QUICKBITE.setForeground(new java.awt.Color(51, 51, 255));
        QUICKBITE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QUICKBITE.setText("QUICKBITE");
        QUICKBITE.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        getContentPane().add(QUICKBITE, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 0, 240, 38));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trial/file (1).jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_loginActionPerformed
        // TODO add your handling code here:
        username = l_username.getText().trim();
        String password = l_password.getText().trim();

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both username and password.");
            return;
        }

        try {
            String sql = "SELECT password FROM users WHERE user_name = ?";
            ps = con.prepareStatement(sql);
            ps.setString(1, username);

            rs = ps.executeQuery();
            if (rs.next()) {
                String dbPassword = rs.getString("password");
                if (password.equals(dbPassword)) {
                    JOptionPane.showMessageDialog(this, "Login successful.");
                    new show_rest(username).setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "The password is incorrect.");
                }
            } else {
                int response = JOptionPane.showConfirmDialog(this, "Account Not found. Want to signup instead?", "Account Not Found", JOptionPane.YES_NO_OPTION);
                if (response == JOptionPane.YES_OPTION) {
                    new register().setVisible(true);
                    this.dispose();
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                if (rs != null) rs.close();
                if (ps != null) ps.close();
            } catch (SQLException e) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_l_loginActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        new register().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerActionPerformed

    private void l_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_usernameActionPerformed

    private void l_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel QUICKBITE;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton l_login;
    private javax.swing.JTextField l_password;
    private javax.swing.JTextField l_username;
    private javax.swing.JLabel login;
    private javax.swing.JLabel password;
    private javax.swing.JButton register;
    private javax.swing.JLabel user_id;
    // End of variables declaration//GEN-END:variables
}
