/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trial;
import javax.swing.*;
import java.sql.*;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Random;
import java.util.ArrayList;
/**
 *
 * @author DELL
 */
public class payment extends javax.swing.JFrame {
    Connection con;
    Statement st;
    PreparedStatement ps;
    ResultSet rs;
    public String orderId;
    private ArrayList<MenuItem> selectedItemsList;
    public String name;
    public String username;
    /**
     * Creates new form payment
     */
    public payment(String orderId, ArrayList<MenuItem>selectedItemsList,String name,String username) {
        initComponents();
         this.orderId=orderId;
        this.selectedItemsList = selectedItemsList;
        this.name=name;
        this.username=username;
        try{
Class.forName("oracle.jdbc.OracleDriver");
JOptionPane.showMessageDialog(this,"Driver Loaded!");
try {
//con = DriverManager.getConnection("jdbc:oracle:thin:@10.6.4.33:1521:orcl",
//        "cse1028","ssn");
con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE",
        "system","kushal");
JOptionPane.showMessageDialog(this,"Connected to Oracle database!");
}
catch (SQLException ex) {
Logger.getLogger(payment.class.getName()).log(Level.SEVERE,null, ex);
JOptionPane.showMessageDialog(this,ex.getMessage());
}
}
        catch(ClassNotFoundException ex){
Logger.getLogger(payment.class.getName()).log(Level.SEVERE,null, ex);
JOptionPane.showMessageDialog(this,ex.getMessage());

} 
    }

    
    private String generatePaymentId() {
        String paymentId = null;
        try {
            // Generate a random 4-digit number
            Random random = new Random();
            int randomNum = random.nextInt(10000); // Generates 0 to 9999
            String formattedRandomNum = String.format("%04d", randomNum); // Format to 4 digits with leading zeros
            
            // Construct the payment ID
            paymentId = "P" + formattedRandomNum;
            
            // Check if payment ID already exists (ensure uniqueness)
            while (isPaymentIdExists(paymentId)) {
                randomNum = random.nextInt(10000); // Regenerate random number
                formattedRandomNum = String.format("%04d", randomNum);
                paymentId = "P" + formattedRandomNum;
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error generating payment ID.");
        }
        return paymentId;
    }

    /**
     * Checks if the given payment ID already exists in the database.
     * @param paymentId Payment ID to check
     * @return True if payment ID exists, false otherwise
     */
    private boolean isPaymentIdExists(String paymentId) {
        boolean exists = false;
        try {
            String sql = "SELECT COUNT(*) AS count FROM payment WHERE pay_id = ?";
            ps = con.prepareStatement(sql);
            ps.setString(1, paymentId);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                int count = rs.getInt("count");
                exists = (count > 0);
            }
        } catch (SQLException ex) {
            Logger.getLogger(payment.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        return exists;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pay_meth = new javax.swing.JTextField();
        pay_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("PAYMENT");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("PAYMENT METHOD");

        pay_btn.setBackground(new java.awt.Color(0, 0, 204));
        pay_btn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        pay_btn.setForeground(new java.awt.Color(255, 255, 255));
        pay_btn.setText("PAY");
        pay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(pay_meth, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pay_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pay_meth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(pay_btn)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_btnActionPerformed
        // TODO add your handling code here:
        try {
            LocalDate currentDate = LocalDate.now();
            java.sql.Date sqlDate = java.sql.Date.valueOf(currentDate);
            //DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MMMM-yyyy");
//String formattedDate = currentDate.format(formatter);


           //Timestamp sysdate = rs.getTimestamp("SYSDATE");
            //String sysdateString = sysdate.toString();
String sql = "insert into payment values(?,?,?,?)";
String str=generatePaymentId();
ps = con.prepareStatement(sql);
ps.setString(1,str);
ps.setString(2, orderId);
ps.setDate(3, sqlDate);
ps.setString(4,pay_meth.getText());
int rowsInserted = ps.executeUpdate();

        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Payment recorded successfully.");
            generateBill(orderId,str);
        } else {
            JOptionPane.showMessageDialog(this, "Failed to record payment.");
        }


        }catch (SQLException ex) {
        Logger.getLogger(payment.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }
    }//GEN-LAST:event_pay_btnActionPerformed

    private void generateBill(String orderId, String paymentId) {
    try {
            
            String restaurantName = name;

            StringBuilder bill = new StringBuilder();
            bill.append("********** ").append(restaurantName).append(" **********\n");
            bill.append("Order ID: ").append(orderId).append("\n");
            bill.append("Payment ID: ").append(paymentId).append("\n");
            bill.append("-------------------------------------\n");
            bill.append(String.format("%-10s %-20s %5s %10s\n", "Item ID", "Item", "Qty", "Price"));
            bill.append("-------------------------------------\n");

            double totalCost = 0.0;

            for (MenuItem item : selectedItemsList) {
                String itemId = item.getItemId();
                String itemName = item.getName();
                int quantity = item.getQuantity();
                double price = item.getPrice();
                totalCost += quantity * price;
                bill.append(String.format("%-10s %-20s %5d %10.2f\n", itemId, itemName, quantity, price));
            }

            bill.append("-------------------------------------\n");
            bill.append(String.format("Total: %38.2f\n", totalCost));
            bill.append("\n*** Thank You ***");

            JTextArea billArea = new JTextArea(bill.toString());
            billArea.setEditable(false);
            JScrollPane scrollPane = new JScrollPane(billArea);

            JFrame billFrame = new JFrame("Bill");
            billFrame.add(scrollPane);
            billFrame.setSize(400, 600);
            billFrame.setVisible(true);
            new delivery_person(name,username,orderId).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(payment.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
}     
    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payment(orderId,selectedItemsList,name,username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton pay_btn;
    private javax.swing.JTextField pay_meth;
    // End of variables declaration//GEN-END:variables
}
